# Stage 1: Build React Frontend
FROM node:18 as frontend-build

WORKDIR /app/frontend
COPY ./frontend/package*.json ./
RUN npm ci

COPY ./frontend ./
RUN npm run build

# Stage 2: Build Flask Backend
FROM python:3.11-slim-buster
WORKDIR /app/backend
COPY ./backend ./
RUN apt-get update -y && apt-get install -y gcc
RUN pip install -r requirements.txt

COPY --from=frontend-build /app/frontend/build ./build

CMD ["gunicorn", "-b", "0.0.0.0:80", "run_server:app"]
# CMD ["python", "run_server.py"]